name: Doctor PR
on:
  workflow_dispatch:
    inputs:
      base_branch_name:
        required: true
        type: string
      base_pull_request_number:
        required: true
        type: string
      review_id:
        required: true
        type: string
      aider_message:
        required: true
        type: string
      author_username:
        required: true
        type: string
jobs:
  doctor-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Doctor PR
        uses: Doctor-PR/dr-pr-action@v0.0.2
        with:
          base_branch_name: ${{inputs.base_branch_name}}
          base_pull_request_number: ${{inputs.base_pull_request_number}}
          review_id: ${{inputs.review_id}}
          aider_message: ${{inputs.aider_message}}
          author_username: ${{inputs.author_username}}
          anthropic_api_key: ${{secrets.ANTHROPIC_API_KEY}}
