name: PR Reviewed

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  make-changes:
    runs-on: ubuntu-latest
    env:
      AIDER_YES_ALWAYS: true
      AIDER_GIT: false
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      AIDER_MESSAGE: ${{github.event.review.body}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Aider
        run: curl -LsSf https://aider.chat/install.sh | sh
      - name: Run Aider
        run: aider
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{github.event.pull_request.head.ref}}
