name: Test

on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "starting"
          echo "github.event.review.body" ${{github.event.review.body}}
          echo "github.event.pull_request.body" ${{github.event.pull_request.body}}
          echo "github.event.pull_request.comments_url" ${{github.event.pull_request.comments_url}}
          echo "github.event.pull_request.review_comment_url" ${{github.event.pull_request.review_comment_url}}
          echo "github.event.pull_request.review_comments_url" ${{github.event.pull_request.review_comments_url}}
          echo "ending"
