name: Test

on:
  pull_request_review_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "starting"
          echo "github.event.comment.body" ${{github.event.comment.body}}
          echo "github.event.comment.path" ${{github.event.comment.path}}
          echo "ending"
